site_name: Desert Garden
site_url: https://desertthunder.github.io/garden
repo_url: https://github.com/desertthunder/garden
repo_name: desertthunder/garden
theme:
  name: material
  icon:
    logo: material/lightning-bolt-circle
    repo: fontawesome/brands/square-github
  favicon: assets/favicon.ico
  font:
    text: "Lexend"
    code: "Roboto Mono"
  features:
    - navigation.indexes
    # - navigation.expand
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra:
  social:
  - icon: octicons/browser-24
    link: https://desertthunder.github.io
  - icon: material/github
    link: https://github.com/desertthunder
copyright: Copyright &copy; 2024 Owais J.
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
      permalink_title: "Link to this section"
      title: Table of Contents
  - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - footnotes
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.details
nav:
  - Home:
    - README.md
  - Books:
    - books/README.md
    - How to Take Smart Notes: writing/book-ahrens-2017.md
    - How to Be Perfect: philosophy/book-schur-2023.md
  - Writing: writing/README.md
  - Learning:
    - Active Inhibition: writing/active_inhibition.md
    - Autonomy in Work: writing/autonomy_in_work.md
    - Cultivating a Digital Garden: writing/cultivation.md
    - Feature Positive Effect: writing/feature_positive_effect.md
    - Goal of Learning: writing/goal_of_learning.md
    - Mere Exposure Effect: writing/mere_exposure_effect.md
    - Motivation When Studying: writing/motivation_when_studying.md
    - Worldly Wisdom: writing/worldly_wisdom.md
    - Write to Learn: writing/write_to_learn.md
  - Psychology:
    - Dealing with Pain: psychology/dealing-with-pain.md
    - Hedonic Treadmill: psychology/hedonic-treadmill.md
    - Indestructible: psychology/indestructible.md
    - Shoshin: psychology/shoshin.md
    - Tsundoku: psychology/tsundoku.md
    - Why We Read: psychology/why-we-read.md
    - IFS: psychology/ifs.md
    - Productivity:
      - The Cult of Done: psychology/productivity/done.md
    - Questionable:
      - Submodality: psychology/submodality.md
  - Engineering:
    - engineering/README.md
    - General:
      - Code Kata: engineering/general/katas.md
      - Daybook: engineering/general/daybooks.md
    - Architecture:
      - Architecture Decision Records: engineering/architecture/adr.md
    - Command Line API Testing: engineering/bash_http.md
    - Databases:
      - DSN: engineering/databases/dsn.md
    - Web:
      - Batteries Included: engineering/web/batteries.md
      - Django:
        - REST Framework:
          - engineering/web/django/rest/README.md
  - Programming:
      - programming/README.md
      - Design Patterns:
        - Adapter: programming/design/adapter.md
      - Languages:
        - Golang:
          - HTTP Requests: programming/golang/http-requests.md
        - Python:
          - Logging: programming/python/logging.md
      - Algorithms:
        - Dijkstra's Algorithm: algorithms/dijkstra.md
        - Selection Sort: algorithms/selection-sort.md
      - Data Structures:
        - data-structures/README.md
        - Arrays:
            - Overview: data-structures/arrays.md
            - Array-like:
                - data-structures/collections/README.md
                - Stacks: data-structures/stacks.md
        - Trees: data-structures/trees.md
  - Philosophy:
    - Aristotle's Problem: philosophy/aristotle-problem.md
    - Bentham's Scale: philosophy/bentham-scale.md
    - Heuristic: philosophy/heuristic.md
    - The Trolley Problem: philosophy/trolley-problem.md
  - Sociology:
    - Broken Windows Policing: sociology/broken-windows.md
plugins:
  - search
  - roamlinks
  - git-revision-date-localized:
        fallback_to_build_date: true
